[package]
name = "advent2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
aoc-client = "*"
log = "0.4.22"
macros = { path = "macros" }
env_logger = "0.11.5"
itertools = "0.13.0"
