[package]
name = "advent2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
aoc-client = "*"
clap = { version = "4.5.21", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4.22"
macros = { path = "macros" }
itertools = "0.13.0"
nom = "7.1.3"
nom-supreme = "0.8.0"
